storage:
  storage-type: MySQL

  database:
    database: "database-name"
    host: "ip-address"
    port: "3306"
    username: "username"
    password: "password"

messages:
  prefix: "&7[&c&lH&6&lS&7] &f"
  commands:
    only-players: "&cOnly players can execute this command!"
    player-no-permission: "&cYou don't have permission to execute this command!"
    player-unknown-command: "&cCommand not found! Use /hideandseek help for more info."