name: HideAndSeek
version: ${project.version}
main: com.exortions.hideandseek.HideAndSeek
api-version: 1.16
authors: [ Exortions ]
description: A single instance mini-game plugin that allows servers to set up a hide-and-seek mini-game for their players.
website: exortions.com
commands:
  hideandseek:
    description: Main command for the Hide and Seek plugin.
    aliases:
      - hs